# Generated by Django 5.1.15 on 2026-09-16 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Student's full name", max_length=100)),
                ('email', models.EmailField(help_text='Unique student email address', max_length=254, unique=True)),
                ('department', models.CharField(help_text='Academic department', max_length=100)),
                ('year', models.IntegerField(help_text='Current academic year (1-4)', validators=[django.core.validators.MinValueValidator(1, message='Year must be at least 1.'), django.core.validators.MaxValueValidator(4, message='Year cannot exceed 4.')])),
                ('cgpa', models.DecimalField(decimal_places=2, help_text='Cumulative GPA on a scale of 0.00 to 10.00', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0, message='CGPA cannot be negative.'), django.core.validators.MaxValueValidator(10.0, message='CGPA cannot exceed 10.00.')])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of student enrollment')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last record update')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-id'],
            },
        ),
    ]
